# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.CharField(default='', max_length=10),
        ),
    ]
