# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_schoolclass'),
        ('students', '0003_remove_student_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Schoolclass'),
        ),
    ]
