# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biobrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.DecimalField(decimal_places=0, max_digits=2)),
                ('coord_y', models.CharField(max_length=1)),
                ('biobrick_type', model_utils.fields.StatusField(choices=[('detector', 'detector'), ('responder', 'responder')], default='detector', max_length=100, no_check_for_status=True)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('design', models.TextField(max_length=1000)),
                ('igem_part', models.TextField(max_length=20)),
                ('team_website', models.TextField(max_length=200)),
                ('dna_sequence', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biosensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('problem_description', models.TextField(max_length=1000)),
                ('risk_description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', model_utils.fields.StatusField(choices=[('detector', 'detector'), ('responder', 'responder'), ('biosensor', 'biosensor')], default='detector', max_length=100, no_check_for_status=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='biosensor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobricks.Category'),
        ),
        migrations.AddField(
            model_name='biosensor',
            name='detector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to='biobricks.Biobrick'),
        ),
        migrations.AddField(
            model_name='biosensor',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='biobricks.Biobrick'),
        ),
        migrations.AddField(
            model_name='biosensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biobrick',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobricks.Category'),
        ),
    ]
