# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', model_utils.fields.StatusField(choices=[('detector', 'detector'), ('responder', 'responder'), ('biobrick', 'biobrick')], default='detector', max_length=100, no_check_for_status=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
