# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biobrick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('design', models.TextField(max_length=1000)),
                ('igem_part_link', models.TextField(max_length=200)),
                ('team_website', models.TextField(max_length=200)),
                ('dna_sequence', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobricks.Category')),
            ],
        ),
    ]
