# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 08:49
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0002_biobrick'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobrick',
            name='biobrick_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='detector', max_length=100, no_check_for_status=True),
        ),
    ]
