# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0002_auto_20160627_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biobrick',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biobricks', to='biobricks.Category'),
        ),
    ]
