# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0003_biobrick_biobrick_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobrick',
            name='name',
            field=models.TextField(default='No name', max_length=100),
            preserve_default=False,
        ),
    ]
