# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0004_biobrick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biosensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('problem_description', models.TextField(max_length=1000)),
                ('risk_description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobricks.Category')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectors', to='biobricks.Biobrick')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='biobricks.Biobrick')),
            ],
        ),
    ]
