# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0004_auto_20170226_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biobrick',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='biobrick',
            name='design',
            field=models.TextField(max_length=10000),
        ),
    ]
