# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-02 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0005_auto_20170302_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biosensor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='biosensor',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='biosensor',
            name='risk_description',
        ),
    ]
