# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biobricks', '0005_biosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosensor',
            name='user',
            field=models.ForeignKey(default=User.objects.filter(is_superuser=True)[0].id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
