# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0006_biosensor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biobrick',
            name='igem_part_link',
        ),
        migrations.AddField(
            model_name='biobrick',
            name='igem_part',
            field=models.TextField(default='BBa_K592009', max_length=20),
            preserve_default=False,
        ),
    ]
