# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0007_auto_20160606_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='biobrick',
            name='coords',
            field=models.CharField(default='0a', max_length=2),
            preserve_default=False,
        ),
    ]
