# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0008_biobrick_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biobrick',
            name='coords',
        ),
        migrations.AddField(
            model_name='biobrick',
            name='coord_x',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biobrick',
            name='coord_y',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
