# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
