# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(default=make_password('1234'), max_length=100),
            preserve_default=False,
        ),
    ]
