# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20170208_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_year', models.PositiveIntegerField()),
                ('letter', models.CharField(max_length=10)),
                ('study_field', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.School')),
            ],
        ),
    ]
