# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_schoolclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='teacher',
        ),
        migrations.AddField(
            model_name='invitation',
            name='school_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Schoolclass'),
        ),
    ]
