# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biobricks', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students', models.TextField(max_length=1000)),
                ('subject', model_utils.fields.StatusField(choices=[('biologi', 'biologi'), ('bioteknologi', 'bioteknologi'), ('kemi', 'kemi'), ('srp', 'srp'), ('teknikfag', 'teknikfag'), ('teknologi', 'teknologi'), ('andet', 'andet')], default='biologi', max_length=100, no_check_for_status=True)),
                ('grade', models.DecimalField(decimal_places=0, max_digits=1)),
                ('letter', models.CharField(max_length=1)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('biosensors', models.ManyToManyField(to='biobricks.Biosensor')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=4000)),
                ('method', models.CharField(max_length=4000)),
                ('results', models.CharField(max_length=4000)),
                ('conclusion', models.CharField(max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('biosensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='biobricks.Biosensor')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='studentgroups.StudentGroup')),
            ],
        ),
    ]
