# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(default='Intet gruppenavn', max_length=100),
            preserve_default=False,
        ),
    ]
