# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='biosensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_report', to='biobricks.Biosensor'),
        ),
    ]
