# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import studentgroups.models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0002_auto_20160628_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=studentgroups.models.do_upload_image),
        ),
    ]
