# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20170219_2254'),
        ('students', '0007_auto_20170219_2254'),
        ('studentgroups', '0005_auto_20170208_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='year',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teachers.School'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
