# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0005_auto_20160610_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='year',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='names',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='email',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='letter',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
    ]
