# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0006_auto_20160610_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=4000)),
                ('method', models.CharField(max_length=4000)),
                ('results', models.CharField(max_length=4000)),
                ('discussion', models.CharField(max_length=4000)),
                ('conclusion', models.CharField(max_length=4000)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.StudentGroup')),
            ],
        ),
    ]
