# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-20 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0007_auto_20170219_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={},
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='teachers.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', to='students.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together=set([('name', 'school_class')]),
        ),
    ]
