# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0008_auto_20170220_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='biosensors',
            field=models.ManyToManyField(blank=True, to='biobricks.Biosensor'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='teachers.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='students.Student'),
        ),
    ]
