# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0008_studentbiosensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentBiosensor',
            new_name='StudentGroupBiosensor',
        ),
        migrations.RenameField(
            model_name='studentgroupbiosensor',
            old_name='student',
            new_name='student_group',
        ),
    ]
