# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0009_auto_20170223_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreport',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='method',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='results',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='student_group',
        ),
    ]
