# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from biobricks.models import Biosensor


class Migration(migrations.Migration):

    dependencies = [
        ('biobricks', '0007_auto_20160606_0810'),
        ('studentgroups', '0010_auto_20160616_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='biosensor',
            field=models.ForeignKey(default=Biosensor.objects.all()[0].id, on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='biobricks.Biosensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='studentgroups.StudentGroup'),
        ),
    ]
