# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0012_auto_20170306_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='contending',
            field=models.BooleanField(default=False),
        ),
    ]
