# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0014_remove_studentreport_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2016, max_digits=4),
            preserve_default=False,
        ),
    ]
