# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 19:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='sidebar',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
